"""add columns

Revision ID: 0ae5574ba4f7
Revises: 
Create Date: 2023-12-11 22:12:37.588309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae5574ba4f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p1_linearity', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('p1_hysteresis', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('p2_linearity', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('p2_hysteresis', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('x_slope', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('x_offset', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('x_linearity', sa.Float(), nullable=False, server_default = "0"))
        batch_op.add_column(sa.Column('x_hysteresis', sa.Float(), nullable=False, server_default = "0"))

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_pressure', sa.Float(), nullable=False, server_default = "0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('air_pressure')

    with op.batch_alter_table('constants', schema=None) as batch_op:
        batch_op.drop_column('x_hysteresis')
        batch_op.drop_column('x_linearity')
        batch_op.drop_column('x_offset')
        batch_op.drop_column('x_slope')
        batch_op.drop_column('p2_hysteresis')
        batch_op.drop_column('p2_linearity')
        batch_op.drop_column('p1_hysteresis')
        batch_op.drop_column('p1_linearity')

    # ### end Alembic commands ###
